name = "RayCast"
uuid = "b34ab1fe-1e7a-11e9-3c85-e50322b2de5d"
authors = ["Colin Summers <me@colinxsummers.com>"]
version = "0.1.0"

[deps]
RoboLib = "79865ad4-1e77-11e9-0337-d56b67668373"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
